# Generated by Django 2.0.4 on 2018-04-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='legaldocs')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Client')),
            ],
        ),
        migrations.DeleteModel(
            name='LegalForm',
        ),
        migrations.AlterField(
            model_name='case',
            name='attorney',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Attorney'),
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Client'),
        ),
    ]
