# Generated by Django 2.0.4 on 2018-04-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180419_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldoc',
            name='name',
            field=models.CharField(default='Document', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legaldoc',
            name='pdf_file',
            field=models.FileField(upload_to='main/legaldocs'),
        ),
    ]
