# Generated by Django 2.0.4 on 2018-04-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180424_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='attorney',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
