# Generated by Django 2.0.4 on 2018-04-25 04:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180424_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_id',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='closed_on',
            field=models.DateField(default=datetime.date(2018, 4, 25)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='case',
            name='opened_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
