# Generated by Django 2.0.4 on 2018-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180425_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='is_next',
            field=models.BooleanField(default=False),
        ),
    ]
