# Generated by Django 2.0.4 on 2018-04-25 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_case_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='attorney',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Attorney'),
        ),
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Client'),
        ),
        migrations.AlterField(
            model_name='legaldoc',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Client'),
        ),
    ]
