# Generated by Django 2.0.4 on 2018-04-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180425_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='closed_on',
            field=models.DateField(blank=True),
        ),
    ]
