# Generated by Django 2.0.4 on 2018-04-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180425_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
