# Generated by Django 2.0.4 on 2018-04-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_attorney_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldoc',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Case'),
        ),
    ]
