# Generated by Django 2.0.4 on 2018-04-28 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_legaldoc_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldoc',
            name='doc_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
